import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import { usePathname } from 'next/navigation'
//import { Transition } from "./transition";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('layout')
  return (

        {children}

  );
}
